#!/usr/bin/env bash

if
  [[ -s "/home/testingboxadmin/.rvm/gems/ruby-2.4.1@global/environment" ]]
then
  source "/home/testingboxadmin/.rvm/gems/ruby-2.4.1@global/environment"
  exec testrb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/testingboxadmin/.rvm/gems/ruby-2.4.1@global/environment'" >&2
  exit 1
fi
